### ISSUE TITLE
Custom send email

### ISSUE THREAD

**Issue by Gum97** [h44z/wg-portal#123] opened 2022-10-17 09:06 UTC
Hi developer.

Thanks for creating this amazing app. i have a question
Is there a way to customize the email sent to the user? 
I want to attach a link to the user manual in the email sent to the user
Thanks u.

**Comment by philippderdiedas** [comment] 2022-10-17 21:53
Duplicate of #41

**Closed** 2022-10-29 14:58 UTC
